version: '2'
networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.1.0/30
services:
  borg:
    image: indiehosters/borg
    environment:
    - BORG_MODE=SERVER
    - SSH_KEY
    volumes:
    - ./etc-ssh:/etc/ssh
    - ${FOLDER}:/backups
    ports:
    - "${PORT}:22"
    networks:
    - back
