borg:
  image: indiehosters/borg
  environment:
  - BORG_MODE=SERVER
  volumes:
  - ./etc-ssh:/etc/ssh
  - ./authorized_keys:/home/borg/.ssh/authorized_keys
  - /data/backups/XXserver-nameXX:/backups
  ports:
  - "XXportXX:22"
